config/routes.rb
NoteApp::Application.routes.draw do
  devise_for :users
  
  root :to => 'pages#welcome'
  
  match 'about' => 'pages#about'
  
  resources :users
  resources :notes
  
  match 'notes/:id/undistracted' => 'notes#undistracted', as: :undistracted
  match 'markdownify' => 'pages#markdownify'
  
  scope 'dashboard' do
    match '' => 'dashboard#index', as: 'dashboard'
    match 'notes' => 'dashboard#notes', as: 'dashboard_notes'
    resources :labels
  end
  
  scope 'api' do
    match 'current_user' => 'users#current'
    resources :labels
    resources :notes
  end

end

app/models/label.rb
class Label < ActiveRecord::Base
  belongs_to :owner, class_name: 'User'
  has_many :notes
  
  def to_param
    "#{id}-#{name.parameterize}"
  end
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :owner, class_name: 'User'
  belongs_to :label
  before_validation :init
  
  scope :recent, order('created_at DESC')
  scope :unlabeled, where('label_id is NULL')
  
  self.per_page = 5
  
  def to_param
    "#{id}-#{title.parameterize}"
  end
  
  def increment_hits
    self.increment!(:hits)
  end
  
  private
  
    def init
      self.hits = 0
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Gravtastic
  gravtastic
  
  has_many :notes, foreign_key: 'owner_id'
  has_many :labels, foreign_key: 'owner_id'
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :token_authenticatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username
  
  validates :username, :presence => true,
                       :uniqueness => true,
                       :format => { :with => /\A[A-Za-z0-9_-]+\Z/ }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include ApplicationHelper
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!
  
  def index
  end
  
  def notes
    @notes = current_user.notes.recent.paginate(page: params[:page])
  end
  
  def labels
    @labels = current_user.labels
  end
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :authorized, only: [:show, :update, :destroy]
  
  def index
    @labels = current_user.labels.all
  end
  
  def show
    if params[:id] == 'unlabeled'
      @label = Label.new(name: 'Unlabeled')
      @notes = current_user.notes.unlabeled.paginate(page: params[:page])
    else
      @label = Label.find(params[:id])
      @notes = @label.notes.recent.paginate(page: params[:page])
    end
  end
  
  def create
    @label = Label.new(params[:label])
    @label.owner = current_user
    
    if @label.save
      redirect_to root_path, :flash => {:success => "Label created!"}
    else
      redirect_to root_path, :flash => {:error => "Label creation failed!"}
    end
  end
  
  def destroy
    # Need to set any notes with this label to nil
    @label = Label.find(params[:id])
    @label.destroy
    redirect_to root_path, flash: { success: 'Label deleted!' }
  end
  
  private
  
    def authorized
      if params[:id] != 'unlabeled'
        @label = Label.find(params[:id])
        redirect_to root_path if @label.owner != current_user
      end
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_filter :authenticate_user!, except: [:show, :undistracted]
  before_filter :authorized, only: [:edit, :update, :destroy]
  
  def index
    @notes = Note.all
  end
  
  def show
    @note = Note.find(params[:id])
    @note.increment_hits
    
    respond_to do |format|
      format.html
      format.text
      format.json
    end
  end
  
  def new
    @note = Note.new
  end
  
  def create
    @note = Note.new(params[:note])
    @note.owner = current_user
    
    if @note.save
      redirect_to @note
    else
      render action: "new"
    end
  end
  
  def edit
    @note = Note.find(params[:id])
  end
  
  def update
    @note = Note.find(params[:id])
    
    if @note.update_attributes(params[:note])
      redirect_to @note
    else
      render :edit
    end
  end
  
  def destroy
    @note = Note.find(params[:id])
    @note.destroy
    redirect_to root_path, flash: { success: 'Note deleted!' }
  end
  
  def undistracted
    @note = Note.find(params[:id])
    render layout: 'undistracted'
  end
  
  private
  
    def authorized
      @note = Note.find(params[:id])
      redirect_to root_path if @note.owner != current_user
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_filter :authenticate_user!, only: [:markdownify]
  
  def welcome
    if(user_signed_in?)
      redirect_to dashboard_path
    end
  end
  
  def about
  end
  
  def markdownify
    render text: markdown(params[:note])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, only: [:current]
  respond_to :html, :json
  
  def index
    respond_with(@users = User.all)
  end
  
  def show
    respond_with(@user = User.find(params[:id]))
  end
  
  def current
    respond_with(current_user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Devise
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
  
  # Redcarpet
  def markdown(text)
    markdown = Redcarpet::Markdown.new(HTMLwithHighlight.new(
      hard_wrap: true, filter_html: true),
      no_intra_emphasis: true, autolink: true, fenced_code_blocks: true,
      lax_html_blocks: true, superscript: true, tables: true, strikethrough: true)
    return markdown.render(text).html_safe
  end
end

class HTMLwithHighlight < Redcarpet::Render::HTML
  def block_code(code, language)
    CodeRay.scan(code, language).div(line_numbers: :table)
  end
  def table(header, body)
    "<table class=\"table table-bordered\">\n<thead>\n#{header}</thead>\n<tbody>\n#{body}</tbody>\n</table>"
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/_note.html.haml
.note
  .note-options
    = link_to '', edit_note_path(note), class: 'icon-edit'
    = link_to '', note, method: :delete, confirm: 'Are you sure you want to delete this note?', class: 'icon-trash'
  .note-title= link_to note.title, note
  .note-timestamp= "Created #{time_ago_in_words(note.created_at)} ago"
  .note-preview
    %pre= truncate(note.content, length: 100)
  .note-footer
    .note-tag
      %i.icon-tag
      -if !note.label.nil?
        = note.label.name
      - else
        None
    -#= note.hits

app/views/dashboard/_sidebar.html.haml
.span3
  #dashboard-sidebar.paper-container
    %section#dashboard-user
      #dashboard-user-left
        = link_to image_tag(current_user.gravatar_url), current_user
      #dashboard-user-right
        %div= "#{current_user.notes.count} notes"
        %div= "#{current_user.labels.count} labels"
    -#%section#dashboard-nav
      %hr
      %ul.nav.nav-list
        %li
          %a{href: root_path}
            %i.icon-big-home
            Home
        -#%li
          %a{href: root_path}
            %i.icon-big-tags
            My Labels
        -#%li
          %a{href: root_path}
            %i.icon-big-eye-open
            Explore
    %section#dashboard-labels
      %hr
      %ul
        %li
          %a{href: dashboard_notes_path, rel: 'tooltip', title: 'All Notes'}
            %i.icon-file
            All Notes
        %li
          %a{href: label_path('unlabeled'), rel: 'tooltip', title: 'Unlabeled'}
            %i.icon-question-sign
            Unlabeled Notes
      %hr
      %ul
        - if current_user.labels.empty?
          %li No Labels
        - else 
          - current_user.labels.each do |l|
            %li
              %a{href: label_path(l), rel: 'tooltip', title: l.name}
                %i.icon-tag
                = l.name
    %hr
    = form_for(Label.new, as: :label, url: labels_path) do |f|
      = f.text_field :name, placeholder: 'New Label', class: 'fluid-input'

app/views/dashboard/index.html.haml
#dashboard.row
  = render 'sidebar'
  .span9.stretch-container
    #dashboard-main.paper-container
      .dashboard-section
        %h1 Recent Notes
        %ul.cards
          - current_user.notes.recent.limit(9).each do |note|
            = render 'shared/note_card', note: note
        -#%h1 Account Info
        -#%p account editing and informations, info about dropbox linking, stats

app/views/dashboard/notes.html.haml
#dashboard.row
  = render 'sidebar'
  .span9.stretch-container
    #dashboard-main
      #dashboard-note-list
        - @notes.each do |note|
          = render 'note', note: note
        = will_paginate @notes, class: 'pagination pagination-centered'

app/views/labels/show.html.haml
#dashboard.row
  = render 'dashboard/sidebar'
  .span9.stretch-container
    #dashboard-main
      #dashboard-label-header
        = @label.name
        - if !@label.id.nil?
          #dashboard-label-options
            = link_to '', @label, method: :delete, confirm: 'Are you sure you want to delete this label?', class: 'icon-trash'
      #dashboard-note-list
        - if @notes.empty?
          #no-labels
            This label is empty
        - else
          - @notes.each do |note|
            = render 'dashboard/note', note: note
          = will_paginate @notes, class: 'pagination pagination-centered'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Noteorious</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'shared/navbar' %>
  <div id="main-container" class="container">
    <%= render 'shared/alerts' %>
    <%= yield %>
  </div>
<%= javascript_include_tag "application" %>
<script type="text/javascript" src="http://use.typekit.com/sgj6yul.js"></script>
<script type="text/javascript">try{Typekit.load();}catch(e){}</script>
<!--<script src="http://scripts.embed.ly/jquery.embedly.min.js"></script>-->
<!--<script type="text/javascript" src="http://anywhere.embed.ly/scripts/7ffb388959334303937562342a1b4ecc.js?t=1332139920"></script>-->
<script type="text/javascript">
  if('<%= controller_name %>' == 'notes' && ('<%= action_name %>' == 'new' || '<%= action_name %>' == 'edit'))
    setInterval(updatePreview, 4000)
  /*$('document').ready(function(){
    $('div#note-content').embedly({
      maxWidth: 450,
      wmode: 'transparent',
      method: 'after',
      key:'a4a48eca673111e1b2ab4040d3dc5c07'
    });
  });*/
</script>
</body>
</html>

app/views/layouts/undistracted.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NoteApp</title>
  <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.4.1/build/cssreset/cssreset-min.css">
  <link rel="stylesheet" type="text/css" href="/css/undistracted.css", media="all">
  <%= csrf_meta_tags %>
</head>
<body>
  <button id="print-button" onclick="print();">Print</button>
  <div id="main-container" class="container">
    <%= yield %>
  </div>
<%= javascript_include_tag "application" %>
</body>
</html>

app/views/notes/_fields.html.haml
= f.text_field :title, placeholder: 'Untitled', class: 'fluid-input'
= f.collection_select :label_id, current_user.labels, :id, :name, {include_blank: 'No Label'}, {class: 'fluid-input'}
= f.text_area  :content, placeholder: 'Content', size: '30x23', class: 'fluid-input'

app/views/notes/edit.html.haml
.row
  .span6.stretch-container
    #note-editor.paper-container
      = form_for(@note, as: :note, url: @note) do |f|
        = render 'notes/fields', f: f
        = f.submit 'Update', class: 'btn btn-primary btn-large', style: 'width: 100%;'
  .span6.stretch-container
    #note-preview.paper-container

app/views/notes/new.html.haml
.row
  .span6.stretch-container
    #note-editor.paper-container
      = form_for(Note.new, :as => :note, :url => notes_path) do |f|
        = render 'notes/fields', f: f
        = f.submit 'Create', class: 'btn btn-primary btn-large', style: 'width: 100%;'
  .span6.stretch-container
    #note-preview.paper-container

app/views/notes/show.html.haml
#note-header
  %h1= @note.title
  %h2
    Created by
    = link_to @note.owner.username, @note.owner
    = "#{time_ago_in_words(@note.created_at)} ago"
  -#if !@note.tag_list.empty?
    %h4
      - @note.tag_list.each do |tag|
        -#= link_to tag, tag_path(tag), class: 'tag'
        %a{href: tag_path(tag), class: 'header-tag'}
          %i.icon-tag.icon-white
          %span= tag
  #note-options
    .btn-group
      %button.btn.btn-large.btn-primary.dropdown-toggle{'data-toggle' => 'dropdown'}
        Options
        %span.caret
      %ul#note-options-button.dropdown-menu
        %li= link_to "View Undistracted", undistracted_path(@note)
        %li= link_to "View Raw", note_path(@note, format: :text)
        - if current_user == @note.owner
          %li.divider
          %li= link_to "Edit", edit_note_path(@note)
#note-content.paper-container
  ~ markdown(@note.content)

app/views/notes/show.text.erb
<%= @note.content %>

app/views/notes/undistracted.html.haml
%header.note-header
  %hgroup
    %h1= @note.title
    %h2.light= "By #{@note.owner.username}"
  %ul
    %li= link_to note_url(@note), @note
= markdown(@note.content)

app/views/pages/about.html.haml
About

app/views/pages/welcome.html.haml
#welcome
  #welcome-header
    %h1= raw("Welcome to #{content_tag 'span', 'Note', class: 'highlight'}orious")
    %h2 A simple way to create and share notes
    = image_tag '/assets/noteorious-screenshot.png'
  #welcome-content
    %h3 Features
    %ul
      %li A simple and easy to use interface
      %li Markdown support
      %li Realtime preview of notes

app/views/shared/_alerts.html.erb
<div id="alert-messages">
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice || name == :success ? 'success' : 'error' %>">
    <a class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>
</div>

app/views/shared/_navbar.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      %a.btn.btn-navbar{'data-toggle' => 'collapse', 'data-target' => '.nav-collapse'}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      =# link_to 'Noteorious', root_path, id: 'center-brand'
      = link_to image_tag('/assets/noteorious-logo.png', id: 'logo'), root_path
      .nav-collapse.pull-right
        - if user_signed_in?
          %form.navbar-search.pull-left
            %input.search-query{type: 'text'}
        %ul.nav.pull-right
          - if !user_signed_in?
            %li.divider-vertical
            %li= link_to 'Sign In', new_session_path(resource_name)
          %li.divider-vertical
          %li.dropdown
            %a.dropdown-toggle{'data-toggle' => 'dropdown'} 
              - if user_signed_in?
                = image_tag current_user.gravatar_url, id: 'navbar-user'
                %b#navbar-user= current_user.username
              - else
                %b Hello Guest
              %b.caret
            %ul.dropdown-menu
              - if user_signed_in?
                %li= link_to "My Profile", current_user
                %li= link_to "Edit Profile", edit_user_registration_path
                %li.divider
                %li= link_to "New Note", new_note_path
                %li.divider
                %li= link_to "Sign Out", destroy_user_session_path, method: :delete
              - else
                #signin-dropdown= render 'shared/sign_in_form'
          %li.divider-vertical
          - if user_signed_in?
            %li= link_to image_tag('/assets/icons/edit-white.png'), new_note_path, id: 'navbar-new-note', class: 'btn btn-primary'
            %li.divider-vertical
          -#%li
            %button.navbar-button.btn.btn-primary{onclick: 'toggleWidth()'}
              View

app/views/shared/_note_card.html.haml
%li.card
  .card-content
    .card-header
      .card-title= link_to note.title, note
      .card-author= "By #{note.owner.username}"
    .card-note
      -#= pin_item_display pin, 'item-thumbnail-image-large'
      %pre= truncate(note.content, length: 100)
    .card-metadata
      .card-label
        %i.icon-tag
        -if !note.label.nil?
          = link_to note.label.name, note.label
        - else
          None
      .card-options
        = link_to '', edit_note_path(note), class: 'icon-edit'
        = link_to '', note, method: :delete, confirm: 'Are you sure you want to delete this note?', class: 'icon-trash'

app/views/shared/_sign_in_form.html.erb
<div id="sign-in-form">
  <%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
    <%= field_set_tag nil, :class => 'control-group' do %>
    <ul class="unstyled">
      <li><%= f.email_field :email, :placeholder => 'E-Mail', :class => 'text-input' %></li>
      <li><%= f.password_field :password, :placeholder => 'Password', :class => 'text-input' %></li>
    </ul>
    <% end %>

    <% if devise_mapping.rememberable? -%>
      <label class="checkbox">
        <%= f.check_box :remember_me, :class => "checkbox" %>
        Remember Me
      </label>
    <% end -%>

    <%= f.submit "Sign in", :class => 'btn btn-primary' %>
  <% end %>

  <%= render 'devise/links' %>
</div>

app/views/users/show.html.haml
#user-info.paper-container
  = image_tag @user.gravatar_url(size: 32)
  %h1= link_to "#{@user.username}'s Profile", @user
  #user-info-data
    - if @user == current_user
      = link_to 'Manage Profile', edit_user_registration_path
.paper-container
  %h1 Notes
  %table.table.table-striped
    %thead
      %tr
        %th Title
        %th Created
        %th Hits
    %tbody
      - @user.notes.recent.each do |note|
        %tr
          %td= link_to note.title, note
          %td= "#{time_ago_in_words(note.created_at)} ago"
          %td= note.hits